trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install --only=production
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'
